app/routes.py
import bcrypt  # Asegúrate de instalar bcrypt
from flask import render_template, redirect, url_for, session, request, flash, Blueprint
import psycopg2
from dotenv import load_dotenv
import os
from itsdangerous import URLSafeTimedSerializer
import smtplib  # o una librería de email más avanzada
from mailjet_rest import Client
import re
from werkzeug.security import generate_password_hash
import csv
from datetime import datetime


load_dotenv()

class database():
    conexion = None
    db = None

    def conectar(self):
        self.conexion = psycopg2.connect(os.environ.get('psql'))
        self.db = self.conexion.cursor()

    def desconectar(self):
        self.conexion.commit()
        self.db.close()
        self.conexion.close()

database_api = database()

def send_email(subject, item_name, to_email):
    # Usar directamente las variables de entorno
    api_key = os.getenv("MAILJET_API_KEY")
    api_secret = os.getenv("MAILJET_API_SECRET")

    if not api_key or not api_secret:
        print("MAILJET_API_KEY o MAILJET_API_SECRET no encontrados.")
        return

    mailjet = Client(auth=(api_key, api_secret), version='v3.1')

    # Estilo inline para el email
    html_content = f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                    color: #333;
                }}
                .container {{
                    width: 100%;
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #fff;
                    border-radius: 8px;
                }}
                h1 {{
                    color: #4CAF50;
                    text-align: center;
                }}
                p {{
                    font-size: 16px;
                    margin-bottom: 15px;
                }}
                .footer {{
                    text-align: center;
                    font-size: 14px;
                    color: #777;
                    margin-top: 20px;
                }}
                .footer a {{
                    color: #4CAF50;
                    text-decoration: none;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>¡Felicidades!</h1>
                <p>Nos complace informarte que tu ítem <strong>{item_name}</strong> ha sido vendido. Solicita un turno para coordinar el pago.</p>
                <p>Gracias por confiar en nosotros.</p>
                <div class="footer">
                    <p>Atira Consignment - Todos los derechos reservados.</p>
                </div>
            </div>
        </body>
    </html>
    """

    data = {
        'Messages': [
            {
                "From": {
                    "Email": "airplugventas@gmail.com",
                    "Name": "Atira Consignment"
                },
                "To": [
                    {
                        "Email": to_email
                    }
                ],
                "Subject": subject,
                "HTMLPart": html_content
            }
        ]
    }

    result = mailjet.send.create(data=data)
    if result.status_code == 200:
        print("Email sent successfully!")
    else:
        print(f"Error sending email: {result.status_code}, {result.text}")

# Función para enviar correo de restablecimiento de contraseña
def send_reset_email(to_email, token):
    reset_url = url_for('main.reset_password', token=token, _external=True)
    subject = "Restablecer tu contraseña"
    html_content = f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                    color: #333;
                }}
                .container {{
                    width: 100%;
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #fff;
                    border-radius: 8px;
                }}
                h1 {{
                    color: #4CAF50;
                    text-align: center;
                }}
                p {{
                    font-size: 16px;
                    margin-bottom: 15px;
                }}
                .footer {{
                    text-align: center;
                    font-size: 14px;
                    color: #777;
                    margin-top: 20px;
                }}
                .footer a {{
                    color: #4CAF50;
                    text-decoration: none;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>¡Has solicitado restablecer tu contraseña!</h1>
                <p>Para restablecer tu contraseña, haz clic en el siguiente enlace:</p>
                <p><a href="{reset_url}">Restablecer mi contraseña</a></p>
                <p>Si no solicitaste este cambio, puedes ignorar este mensaje.</p>
                <div class="footer">
                    <p>Atira Consignment - Todos los derechos reservados.</p>
                </div>
            </div>
        </body>
    </html>
    """

    data = {
        'Messages': [
            {
                "From": {
                    "Email": "airplugventas@gmail.com",
                    "Name": "Atira Consignment"
                },
                "To": [
                    {
                        "Email": to_email
                    }
                ],
                "Subject": subject,
                "HTMLPart": html_content
            }
        ]
    }

    mailjet = Client(auth=(os.getenv("MAILJET_API_KEY"), os.getenv("MAILJET_API_SECRET")), version='v3.1')
    result = mailjet.send.create(data=data)

    if result.status_code == 200:
        print("Reset email sent successfully!")
    else:
        print(f"Error sending reset email: {result.status_code}, {result.text}")




# Flask Blueprint
main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/')
def home():
    return render_template('home.html')

@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        
        # Conectar a la base de datos
        database_api.conectar()
        
        # Consultar si el usuario existe en la base de datos
        query = "SELECT email, password, id, is_admin FROM users WHERE email = %s"
        database_api.db.execute(query, (email,))
        user = database_api.db.fetchone()  # Devuelve una tupla (email, password_hash, id, is_admin)
        
        database_api.desconectar()

        if user:
            db_email, db_password, user_id, is_admin = user

            # Compara la contraseña ingresada con la contraseña almacenada usando bcrypt
            if bcrypt.checkpw(password.encode('utf-8'), db_password.encode('utf-8')):
                session['user'] = db_email
                session['user_id'] = user_id
                session['is_admin'] = is_admin

                if is_admin:
                    session['user_type'] = 'admin'
                else:
                    session['user_type'] = 'user'
                
                return redirect(url_for('main.inventory'))  # Redirige a la página de inventario u otra página relevante
            else:
                flash('Email or password was incorrect', 'error')
        else:
            flash('Email or password was incorrect', 'error')

    # Si no es un POST o si hay un error en el login, se redirige a la misma página (home)
    return render_template('home.html')

@main_blueprint.route('/inventory', methods=['GET', 'POST'])
def inventory():
    if 'user' not in session:
        return redirect(url_for('main.login'))

    user_email = session['user']
    is_admin = session.get('is_admin', False)

    database_api.conectar()

    search_query = ""
    if request.method == 'POST':
        search_query = request.form.get('search_query', '').strip()

    if is_admin:
        query = "SELECT * FROM items WHERE name ILIKE %s AND status NOT IN ('sold', 'paid')"
        database_api.db.execute(query, ('%' + search_query + '%',))
        user_items = database_api.db.fetchall()
    else:
        query = "SELECT * FROM items WHERE user_email = %s AND status NOT IN ('sold', 'paid')"
        database_api.db.execute(query, (user_email,))
        user_items = database_api.db.fetchall()

    # Convertimos las tuplas en diccionarios para un manejo más sencillo en el template
    items_dict = []
    for item in user_items:
        item_dict = {
            'id': item[0],
            'name': item[2],
            'color': item[3],
            'size': item[4],
            'status': item[5],
            'net': item[6],
            'price': item[7],
            'condition': item[8],
            'date': item[9],
            'consignor': item[1]
        }
        items_dict.append(item_dict)

    database_api.desconectar()

    return render_template('inventory.html', items=items_dict, is_admin=is_admin)

@main_blueprint.route('/view_profile/<int:user_id>')
def view_profile(user_id):
    if 'user_type' in session and session['is_admin']:
        database_api.conectar()

        # Obtener información del usuario
        query_user = "SELECT id, email, name FROM users WHERE id = %s"
        database_api.db.execute(query_user, (user_id,))
        user_data = database_api.db.fetchone()

        # Obtener ítems del usuario
        query_items = "SELECT * FROM items WHERE user_id = %s"
        database_api.db.execute(query_items, (user_id,))

app/templates/admin_inventory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Inventory</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <div class="container">
        <h2>Admin Inventory</h2>
        <p>Show all inventory items here.</p>
        <a href="{{ url_for('main.create_item') }}" class="btn">Create New Item</a>
        <a href="{{ url_for('main.logout') }}" class="btn">Logout</a>
    </div>
</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav class="menu">
        <ul>
            <li class="{% if request.endpoint == 'main.inventory' %}active{% endif %}">
                <a href="{{ url_for('main.inventory') }}">Inventory</a>
            </li>
            <li class="{% if request.endpoint == 'main.payout' %}active{% endif %}">
                <a href="{{ url_for('main.payout') }}">Payout</a>
            </li>
            <li class="{% if request.endpoint == 'main.payout_history' %}active{% endif %}">
                <a href="{{ url_for('main.payout_history') }}">Payout history</a>
            </li>
            <li class="{% if request.endpoint == 'main.profile' %}active{% endif %}">
                <a href="{{ url_for('main.profile') }}">Profile</a>
            </li>
            {% if session.get('user_type') == 'admin' %}
            <!-- Solo visible para administradores -->
            <li><a href="{{ url_for('main.pos') }}">POS</a></li>
            {% endif %}
            <li class="{% if request.endpoint == 'main.logout' %}active{% endif %}">
                <a href="{{ url_for('main.logout') }}">Log out</a>
            </li>
        </ul>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/change_password.html
{% extends 'base.html' %}

{% block title %}Cambiar Contraseña{% endblock %}

{% block content %}
<div class="form-container">
    <form action="{{ url_for('main.change_password') }}" class="form-edit" method="POST">
        <label for="current_password">Contraseña Actual:</label>
        <input type="password" id="current_password" name="current_password" required>

        <label for="new_password">Nueva Contraseña:</label>
        <input type="password" id="new_password" name="new_password" required>

        <label for="confirm_password">Confirmar Nueva Contraseña:</label>
        <input type="password" id="confirm_password" name="confirm_password" required>

        <button type="submit" class="btn">Cambiar Contraseña</button>
    </form>
</div>
{% endblock %}

app/templates/create_item.html
{% extends 'base.html' %}

{% block title %}Crear nuevo ítem{% endblock %}

{% block content %}
<div class="item-container">
    <h2>Crear nuevo ítem para {{ user.name }}</h2>

    <form action="{{ url_for('main.create_item', user_id=user.id) }}" class="form-edit" method="POST">
        <label for="name">Nombre del ítem:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="details">Detalles:</label>
        <input type="text" id="details" name="details" required><br>  <!-- Cambié textarea por input -->

        <label for="status">Estado:</label>
        <select id="status" name="status" required>
            <option value="in stock">In stock</option>
            <option value="sold">Sold</option>
            <option value="paid">Paid</option>
            <option value="retired">Retired</option>
        </select><br>

        <label for="net">Net:</label>
        <input type="number" id="net" name="net" required><br>
        
        <label for="price">Price:</label>
        <input type="number" id="price" name="price"><br>

        <button type="submit" class="btn">Crear ítem</button>
    </form>
</div>
{% endblock %}

app/templates/create_user.html
{% extends 'base.html' %}

{% block title %}Crear nuevo usuario{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Crear Nuevo Usuario</h2>

    <!-- Formulario de creación de usuario -->
    <form action="{{ url_for('main.create_user') }}" class="form-edit" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" required>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <label for="role">Rol:</label>
        <select id="role" name="role" required>
            <option value="user">Usuario</option>
            <option value="admin">Administrador</option>
        </select>

        <button type="submit" class="btn">Crear Usuario</button>
    </form>
</div>
{% endblock %}

app/templates/edit_item.html
{% extends 'base.html' %}

{% block title %}Editar ítem{% endblock %}

{% block content %}
<div class="item-container">
    <h2>Editar ítem para {{ item.name }}</h2>

    <form action="{{ url_for('main.edit_item', item_id=item.id) }}" class="form-edit" method="POST">
        <label for="name">Nombre del ítem:</label>
        <input type="text" id="name" name="name" value="{{ item.name }}" required><br>

        <label for="details">Detalles:</label>
        <input type="text" id="details" name="details" value="{{ item.details }}" required><br>  <!-- Cambié textarea por input -->

        <label for="status">Estado:</label>
        <select id="status" name="status" required>
            <option value="in stock" {% if item.status == 'in stock' %}selected{% endif %}>In stock</option>
            <option value="sold" {% if item.status == 'sold' %}selected{% endif %}>Sold</option>
            <option value="paid" {% if item.status == 'paid' %}selected{% endif %}>Paid</option>
            <option value="retired" {% if item.status == 'retired' %}selected{% endif %}>Retired</option>
        </select><br>

        <label for="net">Net:</label>
        <input type="number" id="net" name="net" value="{{ item.net }}" required><br>

        <label for="price">Price:</label>
        <input type="number" id="price" name="price" value="{{ item.price }}"><br>
        <button type="submit" class="btn">Actualizar ítem</button>
    </form>
</div>
{% endblock %}

app/templates/forgot_password.html
<!-- forgot_password.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olvidaste tu contraseña</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <h1>Olvidaste tu contraseña</h1>

    <form class="reset-password-form" action="{{ url_for('main.forgot_password') }}" method="POST">
        <h2>Por favor, ingresa tu correo electrónico</h2>

        <div class="form_input">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required class="input-field">
        </div>

        <div class="form_input">
            <button type="submit">Enviar enlace de restablecimiento</button>
        </div>
    </form>

    <p><a href="{{ url_for('main.home') }}">Regresar al inicio de sesión</a></p>
</body>
</html>

app/templates/home.html
<!-- home.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atira consignment</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <h1>Atira consignment</h1>
    
    <form class="login-form" action="{{ url_for('main.login') }}" method="POST">
        <h2>Welcome, please login</h2>
        
        <!-- Mostrar mensaje flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="alert">
                    {% for category, message in messages %}
                        <div class="{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <div class="form_input">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required class="input-field">
        </div>

        <div class="form_input">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required class="input-field">
        </div>

        <div class="form_input">
            <button type="submit">Sign in</button>
        </div>

        <div class="form_input">
            <a href="{{ url_for('main.forgot_password') }}">¿Olvidaste tu contraseña?</a>
        </div>
    </form>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome to the Home Page</h1>
</body>
</html>

app/templates/inventory.html
{% extends 'base.html' %}

{% block title %}Inventario{% endblock %}

{% block content %}
    <h2>Inventory</h2>

    <!-- Barra de búsqueda -->
    <div class="search-container">
        <input type="text" id="search-input" placeholder="Buscar ítem..." onkeyup="searchItems()">
    </div>

    <table id="items-table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Details</th>
                <th>Status</th>
                <th>Price</th>
                <th>Fecha</th>
                {% if is_admin %}
                <th>Net</th>
                <th>Consignor</th>
                <th>Acciones</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.details }}</td>
                <td>{{ item.status }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.date }}</td>
                {% if is_admin %}
                <td>{{ item.net }}</td>
                <td>{{ item.consignor }}</td>
                <td>
                    <a href="{{ url_for('main.edit_item', item_id=item.id) }}" class="action-link">Editar</a> <!-- Botón para editar -->
                    <a href="{{ url_for('main.delete_item', item_id=item.id) }}" class="action-link" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Script para búsqueda -->
    <script>
        function searchItems() {
            const input = document.getElementById('search-input');
            const filter = input.value.toLowerCase();
            const table = document.getElementById('items-table');
            const tr = table.getElementsByTagName('tr');

            // Iterar a través de todas las filas de la tabla
            for (let i = 1; i < tr.length; i++) {  // Empezamos desde 1 para evitar el encabezado
                let td = tr[i].getElementsByTagName('td')[0];  // Buscar por el primer <td> (el nombre del ítem)
                if (td) {
                    let txtValue = td.textContent || td.innerText;
                    if (txtValue.toLowerCase().indexOf(filter) > -1) {
                        tr[i].style.display = '';  // Mostrar fila
                    } else {
                        tr[i].style.display = 'none';  // Ocultar fila
                    }
                }       
            }
        }
    </script>

{% endblock %}

app/templates/payout.html
{% extends 'base.html' %}

{% block title %}Payout{% endblock %}

{% block content %}
    <h2>Payout</h2>
    {% if items %}
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Details</th>
                <th>Status</th>
                <th>Price</th>
                <th>Fecha</th>
                {% if is_admin %}
                <th>Net</th>
                <th>Consignor</th>
                <th>Acciones</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.details }}</td>
                <td>{{ item.status }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.date }}</td>
                {% if is_admin %}
                <td>{{ item.net }}</td>
                <td>{{ item.consignor }}</td>
                <td>
                    <a href="{{ url_for('main.edit_item', item_id=item.id) }}" class="action-link">Editar</a> <!-- Botón para editar -->
                    <a href="{{ url_for('main.delete_item', item_id=item.id) }}" class="action-link" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>   
    {% else %}
        <p>No items found in payout.</p>
    {% endif %}
{% endblock %}

app/templates/profile_admin.html
{% extends 'base.html' %}

{% block title %}Perfiles de Usuarios{% endblock %}

{% block content %}
    <div class="container">
        <h2>Perfiles de Usuarios</h2>
    
        <!-- Botón para agregar nuevo usuario -->
        <div class="button-container"> <!-- Agregar un contenedor -->
            <a href="{{ url_for('main.create_user') }}" class="new-account">Agregar nuevo usuario</a>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>
                        <a href="{{ url_for('main.view_profile', user_id=user.id) }}" class="user-email">{{ user.email }}</a>
                    </td>
                    <td>
                        <a href="{{ url_for('main.edit_user', user_id=user.id) }}" class="action-link">Editar</a> | 
                        <a href="{{ url_for('main.delete_user', user_id=user.id) }}" class="action-link" onclick="return confirm('Are you sure you want to delete this user?');">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/profile_user.html
{% extends 'base.html' %}

{% block title %}Perfil de Usuario{% endblock %}

{% block content %}
<div class="profile-container">
    <h2 lass="info-user">Perfil de {{ user.name }}</h2>

    <!-- Contenedor para la información del usuario -->
    <div class="user-info">
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Nombre:</strong> {{ user.name }}</p>
    </div>

    <!-- Botón para abrir el formulario de cambio de contraseña -->
    <div class="button-container">
    <button type="button"  id="change-password-btn">Cambiar Contraseña</button>
    </div>
</div>
    <!-- Formulario de cambio de contraseña (inicialmente oculto) -->
    <div id="change-password-form" style="display: none; margin-top: 20px;">
        <form action="{{ url_for('main.change_password') }}" method="POST" class="form_edit">
            <label for="current_password">Contraseña Actual:</label>
            <input type="password" id="current_password" name="current_password" required>

            <label for="new_password">Nueva Contraseña:</label>
            <input type="password" id="new_password" name="new_password" required>

            <label for="confirm_password">Confirmar Nueva Contraseña:</label>
            <input type="password" id="confirm_password" name="confirm_password" required>

            <button type="submit">Actualizar Contraseña</button>
        </form>
</div>

<script>
    // Mostrar/ocultar el formulario de cambio de contraseña al hacer clic en el botón
    document.getElementById('change-password-btn').addEventListener('click', function() {
        const form = document.getElementById('change-password-form');
        if (form.style.display === 'none' || form.style.display === '') {
            form.style.display = 'block';
        } else {
            form.style.display = 'none';
        }
    });
</script>
{% endblock %}

app/templates/view_profile.html
{% extends 'base.html' %}

{% block title %}Perfil de {{ user.name }}{% endblock %}

{% block content %}
<div class="profile-container">
    <h2>Perfil de {{ user.name }}</h2>

    <!-- Contenedor para la información del usuario -->
    <div class="user-info">
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Nombre:</strong> {{ user.name }}</p>
    </div>

    <!-- Botón para agregar un nuevo ítem -->
    <div class="button-container">
        <a href="{{ url_for('main.create_item', user_id=user.id) }}" class="new-account">Add New Item</a>
    </div>

    <!-- Botón para importar ítems -->
    <div class="button-container">
        <label for="file-input" class="new new-account">Importar Ítems</label>
        <input type="file" id="file-input" name="file" accept=".csv" style="display:none" onchange="this.form.submit()" />
        <form action="{{ url_for('main.import_items', user_id=user.id) }}" method="POST" enctype="multipart/form-data">
            <button type="submit" class="btn" style="display:none;">Importar Ítems</button>
        </form>
    </div>
</div> <!-- Cierre del contenedor profile-container -->

    <!-- Tabla de ítems del usuario -->
    <div class="user-items">
        <table>
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Details</th>
                    <th>Status</th>
                    <th>Price</th>
                    <th>Fecha</th>
                    <th>Net</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.details }}</td>
                    <td>{{ item.status }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.date }}</td>
                    <td>{{ item.net }}</td>
                    <td>
                        <a href="{{ url_for('main.edit_item', item_id=item.id) }}" class="action-link">Editar</a>
                        <a href="{{ url_for('main.delete_item', item_id=item.id) }}" class="action-link" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}